import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const relaway = Raleway({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={relaway.className}>{children}</body>
    </html>
  );
}
